apiVersion: v1
kind: Service
metadata:
  name: ms-funcionario-svc
  namespace: sistal
  labels:
    app: ms-funcionario
spec:
  type: ClusterIP
  selector:
    app: ms-funcionario
  ports:
  - port: 8080        # Puerto del servicio (interno del clúster)
    targetPort: 8080 # Puerto del contenedor Go
    protocol: TCP