// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Soporte API",
            "email": "soporte@sistal.cl"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/branches": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Obtiene todas las sucursales disponibles",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sucursales"
                ],
                "summary": "Listar sucursales",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/cargos": {
            "get": {
                "description": "Obtiene la lista de todos los cargos disponibles",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catálogos"
                ],
                "summary": "Listar cargos",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/employees/{userId}/contact": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "employees"
                ],
                "summary": "Actualizar contacto",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID o 'me'",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Datos de contacto",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ContactUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ProfileResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/employees/{userId}/measurements": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "employees"
                ],
                "summary": "Obtener medidas",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID o 'me'",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.MedidasResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "employees"
                ],
                "summary": "Actualizar medidas",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID o 'me'",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Medidas",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateMedidasRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ProfileResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/employees/{userId}/profile": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Obtiene los datos del funcionario por User ID (o \"me\")",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "employees"
                ],
                "summary": "Obtener perfil",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID o 'me'",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ProfileResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/funcionarios": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Obtiene la lista de funcionarios con paginación y filtros",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "funcionarios"
                ],
                "summary": "Listar funcionarios",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Página",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Límite por página",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "ID de la sucursal",
                        "name": "id_sucursal",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "ID del estado",
                        "name": "id_estado",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "ID del género",
                        "name": "id_genero",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "ID del cargo",
                        "name": "id_cargo",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Tallas registradas",
                        "name": "tallas_registradas",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Buscar en nombres, apellidos, RUT, email",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "\"fecha_creación\"",
                        "description": "Campo de ordenamiento",
                        "name": "sort_by",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "\"desc\"",
                        "description": "Orden (asc|desc)",
                        "name": "order",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.PaginatedResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Crea un nuevo funcionario en el sistema (requiere rol admin)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "funcionarios"
                ],
                "summary": "Crear funcionario",
                "parameters": [
                    {
                        "description": "Datos del funcionario",
                        "name": "funcionario",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateFuncionarioRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/funcionarios/buscar/rut/{rut}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Obtiene un funcionario por su RUT",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "funcionarios"
                ],
                "summary": "Obtener funcionario por RUT",
                "parameters": [
                    {
                        "type": "string",
                        "description": "RUT del funcionario",
                        "name": "rut",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/funcionarios/empresa/{id_empresa}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Obtiene todos los funcionarios de una empresa",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "funcionarios"
                ],
                "summary": "Obtener funcionarios por empresa",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la empresa",
                        "name": "id_empresa",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/funcionarios/filter": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Obtiene funcionarios según criterios de filtrado con paginación",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "funcionarios"
                ],
                "summary": "Filtrar funcionarios",
                "parameters": [
                    {
                        "type": "string",
                        "description": "RUT del funcionario",
                        "name": "rut_funcionario",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Email del funcionario",
                        "name": "email",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "ID de la empresa cliente",
                        "name": "id_empresa_cliente",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "ID de la sucursal",
                        "name": "id_sucursal",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "ID del segmento",
                        "name": "id_segmento",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "ID del estado",
                        "name": "id_estado",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "ID del cargo",
                        "name": "id_cargo",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Tallas registradas",
                        "name": "tallas_registradas",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Límite de resultados",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Offset para paginación",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.PaginatedFuncionariosResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/funcionarios/me/stats": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Obtiene las estadísticas del funcionario autenticado",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "funcionarios"
                ],
                "summary": "Obtener estadísticas",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/funcionarios/segmento/{id_segmento}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Obtiene todos los funcionarios de un segmento",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "funcionarios"
                ],
                "summary": "Obtener funcionarios por segmento",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del segmento",
                        "name": "id_segmento",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/funcionarios/sucursal/{id_sucursal}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Obtiene todos los funcionarios de una sucursal",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "funcionarios"
                ],
                "summary": "Obtener funcionarios por sucursal",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la sucursal",
                        "name": "id_sucursal",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/funcionarios/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Obtiene un funcionario por su ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "funcionarios"
                ],
                "summary": "Obtener funcionario",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del funcionario",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Actualiza los datos de un funcionario existente (requiere rol admin)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "funcionarios"
                ],
                "summary": "Actualizar funcionario",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del funcionario",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Datos actualizados",
                        "name": "funcionario",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateFuncionarioRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Desactiva un funcionario del sistema - eliminación lógica (requiere rol admin)",
                "tags": [
                    "funcionarios"
                ],
                "summary": "Eliminar funcionario",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del funcionario",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/funcionarios/{id}/activate": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Activa un funcionario previamente desactivado (requiere rol admin)",
                "tags": [
                    "funcionarios"
                ],
                "summary": "Activar funcionario",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del funcionario",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/funcionarios/{id}/deactivate": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Desactiva un funcionario sin eliminarlo (requiere rol admin)",
                "tags": [
                    "funcionarios"
                ],
                "summary": "Desactivar funcionario",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del funcionario",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/funcionarios/{id}/medidas": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Obtiene las medidas corporales actuales de un funcionario",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "medidas"
                ],
                "summary": "Obtener medidas activas",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del funcionario",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Actualiza las medidas corporales actuales de un funcionario",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "medidas"
                ],
                "summary": "Actualizar medidas",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del funcionario",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Datos actualizados",
                        "name": "medidas",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateMedidasRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Registra las medidas corporales de un funcionario",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "medidas"
                ],
                "summary": "Crear medidas",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del funcionario",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Datos de las medidas",
                        "name": "medidas",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateMedidasRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/funcionarios/{id}/medidas/historial": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Obtiene todo el historial de medidas corporales de un funcionario",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "medidas"
                ],
                "summary": "Obtener historial de medidas",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del funcionario",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/generos": {
            "get": {
                "description": "Obtiene la lista de todos los géneros disponibles",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catálogos"
                ],
                "summary": "Listar géneros",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/transfers": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Solicita un traslado de sucursal para el funcionario autenticado",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "traslados"
                ],
                "summary": "Solicitar traslado",
                "parameters": [
                    {
                        "description": "Datos traslado",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.TransferRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Verifica el estado del servicio",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health Check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.CargoDTO": {
            "type": "object",
            "properties": {
                "id_cargo": {
                    "type": "integer"
                },
                "nombre_cargo": {
                    "type": "string"
                }
            }
        },
        "dto.ContactUpdateRequest": {
            "type": "object",
            "required": [
                "celular",
                "email"
            ],
            "properties": {
                "celular": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                }
            }
        },
        "dto.CreateFuncionarioRequest": {
            "type": "object",
            "required": [
                "apellido_paterno",
                "email",
                "id_cargo",
                "id_genero",
                "id_sucursal",
                "nombres",
                "rut_funcionario"
            ],
            "properties": {
                "apellido_materno": {
                    "type": "string"
                },
                "apellido_paterno": {
                    "type": "string"
                },
                "celular": {
                    "type": "string"
                },
                "direccion": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id_cargo": {
                    "type": "integer"
                },
                "id_empresa_cliente": {
                    "type": "integer"
                },
                "id_estado": {
                    "description": "default: 10 (Activo)",
                    "type": "integer"
                },
                "id_genero": {
                    "type": "integer"
                },
                "id_segmento": {
                    "type": "integer"
                },
                "id_sucursal": {
                    "type": "integer"
                },
                "id_usuario": {
                    "type": "integer"
                },
                "nombres": {
                    "type": "string"
                },
                "rut_funcionario": {
                    "type": "string"
                },
                "telefono": {
                    "type": "string"
                }
            }
        },
        "dto.CreateMedidasRequest": {
            "type": "object",
            "required": [
                "estatura_m"
            ],
            "properties": {
                "cadera_cm": {
                    "type": "number"
                },
                "cintura_cm": {
                    "type": "number"
                },
                "estatura_m": {
                    "type": "number"
                },
                "fecha_inicio": {
                    "type": "string"
                },
                "manga_cm": {
                    "type": "number"
                },
                "pecho_cm": {
                    "type": "number"
                }
            }
        },
        "dto.ErrorResponse": {
            "type": "object",
            "properties": {
                "errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.FieldError"
                    }
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "dto.EstadoDTO": {
            "type": "object",
            "properties": {
                "id_estado": {
                    "type": "integer"
                },
                "nombre_estado": {
                    "type": "string"
                },
                "tabla_estado": {
                    "type": "string"
                }
            }
        },
        "dto.FieldError": {
            "type": "object",
            "properties": {
                "field": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "dto.FuncionarioResponse": {
            "type": "object",
            "properties": {
                "apellido_materno": {
                    "type": "string"
                },
                "apellido_paterno": {
                    "type": "string"
                },
                "cargo": {
                    "$ref": "#/definitions/dto.CargoDTO"
                },
                "celular": {
                    "type": "string"
                },
                "direccion": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "estado": {
                    "$ref": "#/definitions/dto.EstadoDTO"
                },
                "fecha_creacion": {
                    "type": "string"
                },
                "fecha_modificacion": {
                    "type": "string"
                },
                "genero": {
                    "$ref": "#/definitions/dto.GeneroDTO"
                },
                "id_empresa_cliente": {
                    "type": "integer"
                },
                "id_funcionario": {
                    "type": "integer"
                },
                "id_segmento": {
                    "type": "integer"
                },
                "medidas": {
                    "$ref": "#/definitions/dto.MedidasResponse"
                },
                "nombre_completo": {
                    "type": "string"
                },
                "nombres": {
                    "type": "string"
                },
                "rut_funcionario": {
                    "type": "string"
                },
                "sucursal": {
                    "$ref": "#/definitions/dto.SucursalDTO"
                },
                "tallas_registradas": {
                    "type": "boolean"
                },
                "telefono": {
                    "description": "Campos adicionales (no en contrato pero presentes en BD)",
                    "type": "string"
                },
                "usuario": {
                    "$ref": "#/definitions/dto.UsuarioDTO"
                }
            }
        },
        "dto.GeneroDTO": {
            "type": "object",
            "properties": {
                "id_genero": {
                    "type": "integer"
                },
                "nombre_genero": {
                    "type": "string"
                }
            }
        },
        "dto.MedidasResponse": {
            "type": "object",
            "properties": {
                "cadera_cm": {
                    "type": "number"
                },
                "cintura_cm": {
                    "type": "number"
                },
                "estatura_m": {
                    "type": "number"
                },
                "fecha_fin": {
                    "type": "string"
                },
                "fecha_inicio": {
                    "type": "string"
                },
                "id_funcionario": {
                    "type": "integer"
                },
                "id_medidas": {
                    "type": "integer"
                },
                "manga_cm": {
                    "type": "number"
                },
                "pecho_cm": {
                    "type": "number"
                }
            }
        },
        "dto.PaginatedFuncionariosResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.FuncionarioResponse"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        },
        "dto.PaginatedResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "meta": {
                    "$ref": "#/definitions/dto.PaginationMeta"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "dto.PaginationMeta": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        },
        "dto.ProfileResponse": {
            "type": "object",
            "properties": {
                "apellido_materno": {
                    "type": "string"
                },
                "apellido_paterno": {
                    "type": "string"
                },
                "cargo": {
                    "$ref": "#/definitions/dto.CargoDTO"
                },
                "celular": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "medidas": {
                    "$ref": "#/definitions/dto.MedidasResponse"
                },
                "nombres": {
                    "type": "string"
                },
                "rut": {
                    "type": "string"
                },
                "sucursal": {
                    "$ref": "#/definitions/dto.SucursalDTO"
                },
                "tallas_registradas": {
                    "type": "boolean"
                }
            }
        },
        "dto.RolDTO": {
            "type": "object",
            "properties": {
                "id_rol": {
                    "type": "integer"
                },
                "nombre_rol": {
                    "type": "string"
                }
            }
        },
        "dto.SuccessResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "dto.SucursalDTO": {
            "type": "object",
            "properties": {
                "direccion": {
                    "type": "string"
                },
                "estado": {
                    "$ref": "#/definitions/dto.EstadoDTO"
                },
                "estado_sucursal": {
                    "type": "integer"
                },
                "id_sucursal": {
                    "type": "integer"
                },
                "nombre_sucursal": {
                    "type": "string"
                },
                "total_funcionarios": {
                    "type": "integer"
                }
            }
        },
        "dto.TransferRequest": {
            "type": "object",
            "required": [
                "target_branch_id"
            ],
            "properties": {
                "reason": {
                    "type": "string"
                },
                "target_branch_id": {
                    "type": "integer"
                }
            }
        },
        "dto.UpdateFuncionarioRequest": {
            "type": "object",
            "properties": {
                "apellido_materno": {
                    "type": "string"
                },
                "apellido_paterno": {
                    "type": "string"
                },
                "celular": {
                    "type": "string"
                },
                "direccion": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id_cargo": {
                    "type": "integer"
                },
                "id_empresa_cliente": {
                    "type": "integer"
                },
                "id_estado": {
                    "type": "integer"
                },
                "id_genero": {
                    "type": "integer"
                },
                "id_segmento": {
                    "type": "integer"
                },
                "id_sucursal": {
                    "type": "integer"
                },
                "nombres": {
                    "type": "string"
                },
                "telefono": {
                    "description": "Campos adicionales (no en contrato pero presentes en BD)",
                    "type": "string"
                }
            }
        },
        "dto.UpdateMedidasRequest": {
            "type": "object",
            "properties": {
                "cadera_cm": {
                    "type": "number"
                },
                "cintura_cm": {
                    "type": "number"
                },
                "estatura_m": {
                    "type": "number"
                },
                "fecha_fin": {
                    "type": "string"
                },
                "manga_cm": {
                    "type": "number"
                },
                "pecho_cm": {
                    "type": "number"
                }
            }
        },
        "dto.UsuarioDTO": {
            "type": "object",
            "properties": {
                "id_usuario": {
                    "type": "integer"
                },
                "nombre_completo": {
                    "type": "string"
                },
                "nombre_usuario": {
                    "type": "string"
                },
                "rol": {
                    "$ref": "#/definitions/dto.RolDTO"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Autenticación mediante token JWT. Formato: \"Bearer {token}\"",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    },
    "tags": [
        {
            "description": "Operaciones CRUD y gestión de funcionarios",
            "name": "funcionarios"
        },
        {
            "description": "Gestión de medidas corporales de funcionarios",
            "name": "medidas"
        },
        {
            "description": "Endpoints del BFF para funcionarios (perfil y medidas)",
            "name": "employees"
        },
        {
            "description": "Catálogos de datos maestros (cargos, géneros)",
            "name": "catálogos"
        },
        {
            "description": "Gestión de sucursales",
            "name": "sucursales"
        },
        {
            "description": "Solicitudes de traslado",
            "name": "traslados"
        },
        {
            "description": "Health check del servicio",
            "name": "health"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "API Microservicio de Funcionarios",
	Description:      "API RESTful para la gestión integral de funcionarios en el sistema de control de uniformes empresariales",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
